spring:
  profiles:
    active: dev

---
server:
  port: 8080

spring:
  profiles: dev
  application:
    name: config-ribbon-consumer

eureka:
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: consumer-8080
