spring:
  profiles:
    active: dev

---
server:
  port: 9080

spring:
  profiles: dev
  application:
    name: config-zuul-9080

zuul:
  routes:
    firstRoute:
      path: /consumer/**
      serviceId: config-ribbon-consumer
    
  ignored-services: "*"
  prefix: /cloud

