spring:
  profiles:
    active: dev

---
server:
  port: 9080

spring:
  profiles: dev
  application:
    name: config-zuul-9080

eureka:
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: zuul9080.com

zuul:
  routes:
    firstRoute:
      path: /provider-8084/**
      serviceId: config-ribbon-consumer
    
  ignored-services: "*"
  prefix: /cloud

