spring:
  profiles:
    active: dev

---
server:
  port: 8084

spring:
  profiles: dev
  rabbitmq:
    host: 112.74.185.88
    port: 5672
    username: guest
    password: guest
  application:
    name: config-provider-8084
  datasource:
    username: root
    password: 445221
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.74.185.88:3306/cloud-demo-3?serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: provider-8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
